CREATE DATABASE IF NOT EXISTS Campeonato;
USE Campeonato;

CREATE TABLE  IF NOT EXISTS CITY(
	ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    STATE CHAR(2)
);

CREATE  TABLE IF NOT EXISTS SPORT(
	ID TINYINT UNSIGNED NOT NULL PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
	GENDER CHAR(1) NOT NULL,
    ISINDIVIDUAL TINYINT(1) NOT NULL,
    TEAMSIZE TINYINT NOT NULL
);

CREATE TABLE IF NOT EXISTS ETEC(
	NUMBER SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    CITYID SMALLINT UNSIGNED NOT NULL
);

ALTER TABLE ETEC ADD CONSTRAINT FK_ETEC_ETEC
	FOREIGN KEY (CITYID) REFERENCES ETEC(NUMBER);

CREATE TABLE IF NOT EXISTS STUDENT(
	ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    NAME VARCHAR(100) NOT NULL,
    BIRTHDATE DATE,
    GENDER CHAR(1) NOT NULL,
    EMAIL VARCHAR(100) NOT NULL,
    PHONE VARCHAR (20) NOT NULL,
    TEAMID SMALLINT UNSIGNED NOT NULL
); 

ALTER TABLE STUDENT ADD CONSTRAINT FK_STUDENT_STUDENT
	FOREIGN KEY (TEAMID) REFERENCES STUDENT(ID);

CREATE TABLE IF NOT EXISTS TEAM(
	ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    NAME VARCHAR(100),
    CREATEDATE DATETIME,
    ETECNUMBER SMALLINT UNSIGNED NOT NULL,
    SPORTID TINYINT UNSIGNED NOT NULL
);

ALTER TABLE TEAM ADD CONSTRAINT FK_ETEC_TEAM
	FOREIGN KEY (ETECNUMBER) REFERENCES ETEC(NUMBER);
    
ALTER TABLE TEAM ADD CONSTRAINT FK_SPORT_TEAM
	FOREIGN KEY (SPORTID) REFERENCES SPORT(ID);
    
CREATE TABLE IF NOT EXISTS GAME(
	ID SMALLINT UNSIGNED NOT NULL PRIMARY KEY,
    GAMEDATE DATETIME,
    TEAM1POINTS SMALLINT,
    TEAM2POINT SMALLINT,
    SPORTID TINYINT UNSIGNED NOT NULL,
    TEAM1ID SMALLINT UNSIGNED NOT NULL,
    TEAM2ID SMALLINT UNSIGNED NOT NULL
);

ALTER TABLE GAME ADD CONSTRAINT FK_GAME_SPORT
	FOREIGN KEY (SPORTID) REFERENCES SPORT(ID);
    
ALTER TABLE GAME ADD CONSTRAINT FK_GAME_TEAM1
	FOREIGN KEY (TEAM1ID) REFERENCES TEAM(ID);
    
ALTER TABLE GAME ADD CONSTRAINT FK_GAME_TEAM2
	FOREIGN KEY (TEAM2ID) REFERENCES TEAM(ID);